#!/usr/bin/env bash
set -euo pipefail

# This script processes every scene folder inside the provided base directory.
# Each scene folder must contain a Result_txt/layout.txt file generated by
# the layout stage. For every valid scene folder it will run:
#   1. Text-based retrieval (test_retrieval.py)
#   2. CLIP-based retrieval (retrieval_clip.py)
#   3. Scene composition (scene_composition.py)
# The generated assets are stored alongside the existing layout results.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RETRIEVAL_DIR="${SCRIPT_DIR}/space-generator/retrieval"

BASE_OUTPUT_DIR="${1:-${SCRIPT_DIR}/outputs}"

if [ ! -d "$BASE_OUTPUT_DIR" ]; then
  echo "[ERROR] Base output directory not found: $BASE_OUTPUT_DIR" >&2
  exit 1
fi

if [ ! -d "$RETRIEVAL_DIR" ]; then
  echo "[ERROR] Retrieval pipeline directory not found: $RETRIEVAL_DIR" >&2
  exit 1
fi

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

if command_exists python3; then
  PYTHON_BIN="python3"
elif command_exists python; then
  PYTHON_BIN="python"
else
  echo "[ERROR] Neither python3 nor python was found in PATH." >&2
  exit 1
fi

dir_has_content() {
  local target_dir="$1"
  if [ -d "$target_dir" ]; then
    local first_entry
    first_entry=$(find "$target_dir" -mindepth 1 -print -quit)
    [[ -n "$first_entry" ]]
  else
    return 1
  fi
}

TOTAL=0
PROCESSED=0
FAILED=0

while IFS= read -r -d '' layout_file; do
  TOTAL=$((TOTAL + 1))
  scene_dir="$(dirname "$(dirname "$layout_file")")"
  prompt_name="$(basename "$scene_dir")"

  echo "============================================================"
  echo "Processing scene: $prompt_name"
  echo "Layout file: $layout_file"

  result_txt_dir="$(dirname "$layout_file")"
  retrieval_root="$scene_dir/Result_retrieval"
  text_retrieval_dir="$retrieval_root/text_retrieval"
  clip_retrieval_dir="$retrieval_root/clip_retrieval"
  result_dir="$scene_dir/Result"

  mkdir -p "$text_retrieval_dir" "$clip_retrieval_dir" "$result_dir"

  stage_failed=false

  echo "[1/3] Text retrieval"
  if dir_has_content "$text_retrieval_dir"; then
    echo "  - Existing results detected, skipping."
  else
    if (cd "$RETRIEVAL_DIR" && "$PYTHON_BIN" test_retrieval.py --layout_path "$layout_file" --output_dir "$text_retrieval_dir"); then
      echo "  ✓ Text retrieval completed."
    else
      echo "  ✗ Text retrieval failed. Moving to next scene." >&2
      stage_failed=true
    fi
  fi

  if [ "$stage_failed" = true ]; then
    FAILED=$((FAILED + 1))
    continue
  fi

  echo "[2/3] CLIP retrieval"
  if dir_has_content "$clip_retrieval_dir"; then
    echo "  - Existing results detected, skipping."
  else
    if (cd "$RETRIEVAL_DIR" && "$PYTHON_BIN" retrieval_clip.py --layout_path "$layout_file" --candidate_folder "$text_retrieval_dir" --output_dir "$clip_retrieval_dir"); then
      echo "  ✓ CLIP retrieval completed."
    else
      echo "  ✗ CLIP retrieval failed. Moving to next scene." >&2
      stage_failed=true
    fi
  fi

  if [ "$stage_failed" = true ]; then
    FAILED=$((FAILED + 1))
    continue
  fi

  echo "[3/3] Scene composition"
  if dir_has_content "$result_dir" && find "$result_dir" -type f -name '*.glb' -print -quit >/dev/null 2>&1; then
    echo "  - Existing GLB detected, skipping."
  else
    if (cd "$RETRIEVAL_DIR" && "$PYTHON_BIN" scene_composition.py --root "$result_txt_dir" --clip-results "$clip_retrieval_dir" --output "$result_dir"); then
      echo "  ✓ Scene composition completed."
    else
      echo "  ✗ Scene composition failed. Moving to next scene." >&2
      stage_failed=true
    fi
  fi

  if [ "$stage_failed" = true ]; then
    FAILED=$((FAILED + 1))
    continue
  fi

  PROCESSED=$((PROCESSED + 1))
  echo "Scene completed: $prompt_name"
  echo "Output directory: $result_dir"

done < <(find "$BASE_OUTPUT_DIR" -type f -path '*/Result_txt/layout.txt' -print0)

echo "============================================================"
echo "Summary"
echo "  Total scenes discovered : $TOTAL"
echo "  Scenes completed        : $PROCESSED"
echo "  Scenes failed            : $FAILED"

echo "Done."
